import { relations, sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * The sellable catalogue.
 *
 * This is **pricing, not content**. The 259 service pages on lawxygen.in stay exactly as
 * they are — they carry the organic search value and are not being migrated. What lives
 * here is the part a client can buy: title, price, turnaround, and whether it is on sale
 * at all. The two are joined on the slug the marketing site already generates.
 */

/**
 * A filing done on the client's behalf, versus time with a professional.
 *
 * The distinction is not cosmetic: 22 slugs appear in two categories at once, always as
 * a done-for-you service in `tax-compliance` or `intellectual-property` that also exists
 * as a consultation under a `talk-*` category. `gst-audit-support` is both. They are
 * different products at different prices and must not be collapsed.
 */
export const fulfilmentTypeEnum = pgEnum("fulfilment_type", ["service", "consultation"]);

export const categories = pgTable(
  "categories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** Matches the marketing site's category segment, e.g. `business-setup`. */
    slug: text("slug").notNull(),
    label: text("label").notNull(),
    /** The category's accent colour on the marketing site, carried through for parity. */
    accent: text("accent"),
    position: integer("position").notNull().default(0),
    active: boolean("active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    uniqueIndex("categories_slug_uq").on(t.slug),
    index("categories_position_idx").on(t.position),
  ],
);

export const services = pgTable(
  "services",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "restrict" }),

    /**
     * Generated by the marketing site's `serviceSlug()`, reused verbatim by the seed.
     * NOT unique on its own: 259 services yield only 237 distinct slugs.
     */
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    summary: text("summary"),

    fulfilmentType: fulfilmentTypeEnum("fulfilment_type").notNull().default("service"),

    /** Integer paise. Never a float, and never without its currency. */
    pricePaise: bigint("price_paise", { mode: "number" }),
    currency: text("currency").notNull().default("INR"),
    turnaroundDays: integer("turnaround_days"),

    /** Sellable. Guarded by a CHECK so this cannot be true without a price. */
    active: boolean("active").notNull().default(false),
    /** Drives the "New in Lawxygen" row. Editorial, so admin owns it, not a timestamp. */
    featured: boolean("featured").notNull().default(false),
    position: integer("position").notNull().default(0),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // The catalogue key. A unique index on slug alone would reject 44 of the 259 rows.
    uniqueIndex("services_category_slug_uq").on(t.categoryId, t.slug),
    index("services_active_idx").on(t.active, t.categoryId, t.position),
    index("services_featured_idx")
      .on(t.featured)
      .where(sql`${t.featured}`),

    /**
     * A published service always has a price and a turnaround.
     *
     * This is the difference the database makes: "we forgot to price it" becomes
     * impossible rather than becoming a checkout showing ₹0. Seeded rows start inactive
     * precisely because the catalogue arrives without prices.
     */
    check(
      "services_priced_when_active",
      sql`NOT ${t.active} OR (${t.pricePaise} IS NOT NULL AND ${t.turnaroundDays} IS NOT NULL)`,
    ),
    check("services_price_non_negative", sql`${t.pricePaise} IS NULL OR ${t.pricePaise} >= 0`),
  ],
);

export const categoriesRelations = relations(categories, ({ many }) => ({
  services: many(services),
}));

export const servicesRelations = relations(services, ({ one }) => ({
  category: one(categories, { fields: [services.categoryId], references: [categories.id] }),
}));

export type Category = typeof categories.$inferSelect;
export type Service = typeof services.$inferSelect;
export type FulfilmentType = (typeof fulfilmentTypeEnum.enumValues)[number];
